#Expyriment 1.0.0 (Python 3.10.5), .xpe-file, coding: UTF-8
#date: Sun Sep 21 2025 00:09:36
#sha1: 9e20fe
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='eoghan-Precision-7530', release='6.8.0-79-generic', version='#79-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 12 14:42:46 UTC 2025', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
1944,design,log,
#design: #exp: Launching Disrupt Space
#design: block_cnt,block_id,trial_cnt,trial_id
1944,design,logged,
1944,Experiment,started
1944,stderr,received,'Traceback (most recent call last):'
1944,stderr,received,'  File "/home/eoghan/Documents/cog_sup/experimental_app/PPE/Week-2/Exercises/launching_function.py", line 55, in <module>'
1944,stderr,received,'    launching_function()'
1944,stderr,received,'  File "/home/eoghan/Documents/cog_sup/experimental_app/PPE/Week-2/Exercises/launching_function.py", line 34, in launching_function'
1944,stderr,received,'    while condition:'
1944,stderr,received,"UnboundLocalError: local variable 'condition' referenced before assignment"
